### ISSUE TITLE
Naming conflict for class 'text'

### ISSUE THREAD

**Issue by jeroen** [patperry/corpus#1]
The new `$.text` methods introduced in 0.5.0 has created a conflict with ggplot2. It seem to trigger the very unfortunately named `grid:::validDetails.text`.

```r
library(corpus)
library(ggplot2)
ggplot(cars, aes(x = speed)) + geom_bar()
# Error in `$.text`(x, "label") : $ operator is invalid for text objects
```

Not sure if this is a bug in ggplot2 or corpus. @hadley.

**Comment by patperry** [comment]
Thanks for the heads up. This seems like a bug in ggplot2, but maybe it's best if I work around it by renaming the class to `corpus_text`. (p.s. this issue really belongs on https://github.com/patperry/r-corpus , not here)

**Comment by patperry** [comment]
Also, it's weird that this didn't show up before; the `$.text` method was there in version 0.4.0. I think the problem has to do with corpus importing Matrix, which imports grid. (Version 0.4.0 did not import or use anything from Matrix.)

**Comment by jeroen** [comment]
I think it gets triggered because you [added](https://github.com/cran/corpus/commit/0b90a057cce1899622dbdc7e5385338b7af9d45c#diff-7347fe5a0f184f79ef064e92e3beb297R23) `S3method(`$`, text)` to the `NAMESPACE`.

**Comment by patperry** [comment]
Fixed now: https://github.com/patperry/r-corpus/commit/3d9f299df749d19abe9bd9e484d408b0270bc4ae . I'll submit a new version to CRAN (0.5.1).

**Comment by jeroen** [comment]
Maybe try running the [benchmark.Rmd](https://github.com/jeroen/ndjson-benchmark) script before submitting.

**Comment by patperry** [comment]
Great suggestion. I'll make sure everything runs smoothly before I submit.

**Comment by patperry** [comment]
Just submitted version 0.5.1 to CRAN. Benchmarks runs smoothly now (slightly faster read time, and faster manipulation times). No need for the "as.character" call in the last benchmark any more.
